### ISSUE TITLE
Proposal: link to ooth

### ISSUE THREAD

**Issue by nickredmark** [futurestudio/nodejs-account-boilerplate#16]
This package still appears quite high in search results, but it is outdated. I'm the author of [ooth](http://github.com/nmaro/ooth), a user accounts library built on top of passport.js with many boilerplate examples. I've been actively developing it for almost a year now. Here's a proposal: if you look at it and believe it's legit, would you please link to that project in your project description? Thanks for your consideration.

**Comment by marcuspoehls** [comment]
@nmaro Hi Nick, thank you for thinking of us and reaching out to link ooth. We have an actively maintained and related project ourselves. That’s why we’re not interested linking to your platform at this point. Thanks again for reaching out!
